#ifndef FKL_BUILTIN_H
#define FKL_BUILTIN_H
#include"symbol.h"

typedef enum
{
	FKL_SYMUNDEFINE=1,
	FKL_SYNTAXERROR,
	FKL_INVALIDEXPR,
	FKL_INVALIDTYPEDEF,
	FKL_CIRCULARLOAD,
	FKL_INVALIDPATTERN,
	FKL_WRONGARG,
	FKL_STACKERROR,
	FKL_TOOMANYARG,
	FKL_TOOFEWARG,
	FKL_CANTCREATETHREAD,
	FKL_THREADERROR,
	FKL_MACROEXPANDFAILED,
	FKL_CALL_ERROR,
	FKL_LOADDLLFAILD,
	FKL_INVALIDSYMBOL,
	FKL_LIBUNDEFINED,
	FKL_UNEXPECTEOF,
	FKL_DIVZERROERROR,
	FKL_FILEFAILURE,
	FKL_INVALIDMEMBER,
	FKL_NOMEMBERTYPE,
	FKL_NONSCALARTYPE,
	FKL_INVALIDASSIGN,
	FKL_INVALIDACCESS,
	FKL_IMPORTFAILED,
	FKL_INVALID_MACRO_PATTERN,
	FKL_FAILD_TO_CREATE_BIG_INT_FROM_MEM,
	FKL_LIST_DIFFER_IN_LENGTH,
	FKL_CROSS_C_CALL_CONTINUATION,
}FklBuiltInErrorType;

typedef struct FklCompEnv FklCompEnv;
typedef struct FklVMenv FklVMenv;
typedef struct FklVMheap FklVMheap;

void fklInitCompEnv(FklCompEnv* curEnv);
void fklInitGlobEnv(FklVMenv*,FklVMheap*);
FklSid_t fklGetBuiltInErrorType(FklBuiltInErrorType);
#endif
