#ifndef FAKEVM_H
#define FAKEVM_H
#include"fakedef.h"
#include<pthread.h>

typedef struct Cirular_Ref_List
{
	VMpair* pair;
	int32_t count;
	struct Cirular_Ref_List* next;
}CRL;

int runFakeVM(FakeVM*);
void writeVMvalue(VMvalue*,FILE*,CRL**);
void princVMvalue(VMvalue*,FILE*,CRL**);
FakeVM* newFakeVM(ByteCode*);
FakeVM* newTmpFakeVM(ByteCode*);
FakeVM* newThreadVM(VMproc*,VMheap*);
void initGlobEnv(VMenv*,VMheap*,SymbolTable*);
int B_dummy(FakeVM*);
int B_push_nil(FakeVM*);
int B_push_pair(FakeVM*);
int B_push_int(FakeVM*);
int B_push_chr(FakeVM*);
int B_push_dbl(FakeVM*);
int B_push_str(FakeVM*);
int B_push_sym(FakeVM*);
int B_push_byte(FakeVM*);
int B_push_chan(FakeVM*);
int B_push_var(FakeVM*);
int B_push_env_var(FakeVM*);
int B_push_car(FakeVM*);
int B_push_cdr(FakeVM*);
int B_push_top(FakeVM*);
int B_push_proc(FakeVM*);
int B_push_list_arg(FakeVM*);
int B_pop_var(FakeVM*);
int B_pop_arg(FakeVM*);
int B_pop_rest_arg(FakeVM*);
int B_pop_car(FakeVM*);
int B_pop_cdr(FakeVM*);
int B_pop_ref(FakeVM*);
int B_pop_env(FakeVM*);
int B_swap(FakeVM*);
int B_pack_cc(FakeVM*);
int B_add(FakeVM*);
int B_sub(FakeVM*);
int B_mul(FakeVM*);
int B_div(FakeVM*);
int B_rem(FakeVM*);
int B_atom(FakeVM*);
int B_null(FakeVM*);
int B_set_tp(FakeVM*);
int B_set_bp(FakeVM*);
int B_invoke(FakeVM*);
int B_res_tp(FakeVM*);
int B_pop_tp(FakeVM*);
int B_res_bp(FakeVM*);
int B_file(FakeVM*);
int B_dll(FakeVM*);
int B_chr(FakeVM*);
int B_int(FakeVM*);
int B_dbl(FakeVM*);
int B_str(FakeVM*);
int B_sym(FakeVM*);
int B_byte(FakeVM*);
int B_type(FakeVM*);
int B_nth(FakeVM*);
int B_length(FakeVM*);
int B_appd(FakeVM*);
int B_eq(FakeVM*);
int B_eqn(FakeVM*);
int B_equal(FakeVM*);
int B_gt(FakeVM*);
int B_ge(FakeVM*);
int B_lt(FakeVM*);
int B_le(FakeVM*);
int B_not(FakeVM*);
int B_jmp_if_true(FakeVM*);
int B_jmp_if_false(FakeVM*);
int B_jmp(FakeVM*);
int B_read(FakeVM*);
int B_getb(FakeVM*);
int B_write(FakeVM*);
int B_putb(FakeVM*);
int B_princ(FakeVM*);
int B_dlsym(FakeVM*);
int B_go(FakeVM*);
int B_chanl(FakeVM*);
int B_send(FakeVM*);
int B_recv(FakeVM*);
int B_error(FakeVM*);
int B_raise(FakeVM*);
VMstack* newVMstack(int32_t);
void freeVMstack(VMstack*);
void stackRecycle(FakeVM*);
VMrunnable* newVMrunnable(VMproc*,VMrunnable*);
int createNewThread(FakeVM*);
FakeVMlist* newThreadStack(int32_t);
VMrunnable* hasSameProc(VMproc*,ComStack*);
int isTheLastExpress(const VMrunnable*,const VMrunnable*,const FakeVM* exe);
VMheap* newVMheap();
void createCallChainWithContinuation(FakeVM*,VMcontinuation*);
void freeVMheap(VMheap*);
void freeAllVMs();
void deleteCallChain(FakeVM*);
void joinAllThread();
void cancelAllThread();
void GC_mark(FakeVM*);
void GC_markValue(VMvalue*);
void GC_markValueInStack(VMstack*);
void GC_markValueInEnv(VMenv*);
void GC_markValueInCallChain(ComStack*);
void GC_markMessage(QueueNode*);
void GC_markSendT(QueueNode*);
void GC_sweep(VMheap*);
void GC_compact(VMheap*);

void DBG_printVMenv(VMenv*,FILE*);
void DBG_printVMvalue(VMvalue*,FILE*);
void DBG_printVMstack(VMstack*,FILE*,int);
void DBG_printVMByteCode(uint8_t* code,uint32_t s,uint32_t c,FILE*);
#endif
